---

- name: Nginx Playbook
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Install Python # NOTE: This is the only imperative code. Everything else must be declarative.
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - name: Install nginx
      apt:
        name: nginx
        state: present
